[package]
name = "rust-backend-curie"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "./database" }
api = { path = "./api" }
auth = { path = "./auth" }

[workspace]
members = [
    "api",
    "database",
    "auth"
]
resolver = "2"
