[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel.workspace = true
rocket.workspace = true
serde.workspace = true


bcrypt = "0.17.0"
database = { path = "../database" }
jsonwebtoken = "9.3.0"

