[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel.workspace = true
rocket.workspace = true
serde.workspace = true

chrono = { version = "0.4.39", features = ["serde"] }
dotenvy = "0.15"

